version: '3.8'

services:
  db:
    image: postgres:14
    container_name: phishtrap_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: phishtrap
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: phishtrap_redis
    ports:
      - '6379:6379'

volumes:
  db_data:
